### PR TITLE
Added Initial Login UI

### PR DESCRIPTION
**Pull request by adrean-hipe**

### CODE REVIEW

**Review by hipe-francis — APPROVED** [review]
LGTM 🚀

**Review by hipe01mark — APPROVED** [review]
LGTM 🙇

**Review by bpocrafael — APPROVED** [review]
LGTM 🐑

**Comment by nadj1233** [comment]
LGTM ✨

**Review by nadj1233 — APPROVED** [review]

**Review by hipe01mark — COMMENTED** [review]
LGTM

**Pull request merged**
